forumSTM/src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostsRepository::class)]
class Posts
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;


    #[ORM\ManyToOne(inversedBy: 'posts')]
    private ?User $author;


    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\ManyToOne(inversedBy: 'posts')]
    private ?Category $Category = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'posts')]
    private Collection $comments;


    public function __construct()
    {
        $now = new \DateTimeImmutable();
        $this->createdAt = $now;
        $this->updatedAt = $now;
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): static
    {
        $this->author = $author;

        return $this;
    }


    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): static
    {
        $this->Category = $Category;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPosts($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPosts() === $this) {
                $comment->setPosts(null);
            }
        }

        return $this;
    }


}

forumSTM/src/Form/PostsForm.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Posts;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostsForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Posts::class,
        ]);
    }
}

forumSTM/src/Controller/PostsController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Posts;
use App\Form\CommentForm;
use App\Form\PostsForm;
use App\Repository\CommentRepository;
use App\Repository\PostsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/posts')]
final class PostsController extends AbstractController
{
    #[Route(name: 'app_posts_index', methods: ['GET'])]
    public function index(PostsRepository $postsRepository, PaginatorInterface $paginator, Request $request): Response
    {

        $postsQuery = $postsRepository->findAll();

        $posts = $paginator->paginate(
            $postsQuery, /* query NOT result */
            $request->query->getInt('page', 1), /* page number */
            10 /* limit per page */
        );

        return $this->render('posts/index.html.twig', [
            'posts' => $posts,
        ]);
    }

    #[Route('/new', name: 'app_posts_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $post = new Posts();
        $form = $this->createForm(PostsForm::class, $post);
        $form->handleRequest($request);
        $user = $this->getUser();

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setAuthor($user);
            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('app_posts_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('posts/new.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_posts_show', methods: ['GET', 'POST'])]
    public function show(Posts $post, Request $request, EntityManagerInterface $entityManager, CommentRepository $commentRepository): Response
    {


        $comment = new Comment();
        $form = $this->createForm(CommentForm::class, $comment);
        $form->handleRequest($request);
        $user = $this->getUser();
     $comments = $commentRepository->findBy(['posts' => $post], ['createdAt' => 'DESC']);
     $commentsNumber = count($comments);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setAuthor($user);
            $comment->setPosts($post);
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('app_posts_show', ['id' => $post->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('posts/show.html.twig', [
            'post' => $post,
            'form' => $form,
            'comments' => $comments,
            'commentsNumber' => $commentsNumber,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_posts_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Posts $post, EntityManagerInterface $entityManager): Response
    {
        if ($this->getUser() !== $post->getAuthor()) {
            return $this->redirectToRoute('app_posts_index', [], Response::HTTP_SEE_OTHER);
        }

        $form = $this->createForm(PostsForm::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_posts_show', ['id' => $post->getId()], Response::HTTP_SEE_OTHER);
        }

        return $this->render('posts/edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/delete', name: 'app_posts_delete', methods: ['POST'])]
    public function delete(Request $request, Posts $post, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $post->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($post);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_posts_index', [], Response::HTTP_SEE_OTHER);
    }
}

forumSTM/templates/posts/_delete_form.html.twig
<form method="post" action="{{ path('app_posts_delete', {'id': post.id}) }}" onsubmit="return confirm('Vous êtes sur de vouloir effacer ce sujet?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn">Supprimer</button>
</form>

forumSTM/templates/posts/_form.html.twig
{{ form_start(form, {'action': form_action|default(path('app_posts_new'))}) }}

{{ form_label(form.category, "Catégorie", {'label_attr': {'class': 'form-label'}}) }}
 {{ form_widget(form.category, {'attr': {'class': 'form-input', 'placeholder': 'Titre du sujet'}}) }}
    {{ form_errors(form.category) }}

 {{ form_label(form.title, "Titre", {'label_attr': {'class': 'form-label'}}) }}
 {{ form_widget(form.title, {'attr': {'class': 'form-input', 'placeholder': 'Titre du sujet'}}) }}
    {{ form_errors(form.title) }}

<div class="form-group">
    {{ form_label(form.content, "Contenu", {'label_attr': {'class': 'form-label'}}) }}
    {{ form_widget(form.content, {'attr': {'class': 'form-input plus', 'placeholder': 'Écrivez votre message ici'}}) }}
    {{ form_errors(form.content) }}
</div>

<button class="btn btn-secondary">{{ button_label|default('Enregistrer') }}</button>

{{ form_end(form) }}

forumSTM/templates/posts/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Posts{% endblock %}

{% block body %}
    <h1>Edit Posts</h1>

    {{ include('posts/_form.html.Twig', {
        'form': form,
        'button_label': 'Update',
        'form_action': path('app_posts_edit', {'id': post.id})
    }) }}

    <a href="{{ path('app_posts_index') }}">back to list</a>


{% endblock %}

forumSTM/templates/posts/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sujets{% endblock %}

{% block body %}

    <div class="container">

           <!-- Topics Container -->
        <div class="recent-topics">
            <div class="topic-list">
                {% if app.user %}
                    <a class="btn btn-primary" id="addbtn" href="{{ path('app_posts_new') }}"><span
                            style="font-weight:bold;">&#43;</span> Nouveau Sujet</a>
                {% endif %}
                {% for post in posts %}

                    <div class="topic-item" data-title={{ post.title }}
                         style="cursor:pointer;"
                         onclick="window.location.href='{{ path('app_posts_show', {'id': post.id}) }}'">
                        <div class="avatar">
                            {{ post.author.firstName|slice(0, 1)|upper }}{{ post.author.lastName|slice(0, 1)|upper }}
                        </div>
                        <div class="topic-info">
                            <div class="topic-title">{{ post.title }}</div>
                            <div><p class="post-excerpt">{{ post.content|slice(0, 150) ~ '...' }}</p></div>
                            <div class="topic-meta">
                                <span>👤 {{ post.author.firstName }} {{ post.author.lastName }} </span>
                                <span>&nbsp; 📅 {{ post.createdAt|relative_time }}</span>
                                <span class="category-tag dev">&nbsp;{{ post.category.name }}</span>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <p>Aucun sujet trouvé.</p>
                {% endfor %}
            </div>
            <div class="navigation">
                {{ knp_pagination_render(posts) }}
            </div>
        </div>
    </div>
{% endblock %}

forumSTM/templates/posts/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Posts{% endblock %}

{% block body %}

    <div class="container">
        <a class="retour" href="{{ path('app_posts_index') }}">Retour à la liste</a>
        <h1 class="sectionTitle">Créer un nouveau sujet</h1>

        {{ include('posts/_form.html.twig', {
            'form': form,
            'button_label': 'Enregistrer',
            'form_action': path('app_posts_new')
        }) }}


    </div>
{% endblock %}

forumSTM/templates/posts/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sujets{% endblock %}

{% block body %}
    <div class="container">
        <div class="topic-header">
            <h1 class="topic-title">{{ post.title }}</h1>
            <div class="topic-meta">
                <div
                    class="avatar">{{ post.author.firstName|slice(0, 1)|upper }}{{ post.author.lastName|slice(0, 1)|upper }}</div>
                <span>Créé par <strong>{{ post.author.firstName }} {{ post.author.lastName }}</strong></span>
                <span>•</span>
                <span>📅 {{ post.createdAt|relative_time }}</span>
                <span>•</span>
                <span>{{ post.category.name }}</span>
                {% if app.user and app.user.id == post.author.id %}

                    {{ include('posts/_delete_form.html.twig') }}
                    <button class="btn btn-secondary"
                            onclick="window.location.href='{{ path('app_posts_edit', {'id': post.id}) }}'">Editer
                    </button> {% endif %}

            </div>
            <div>{{ post.content }}</div>
            <div class="topic-stats">
                <div class="stat">
                    <div class="stat-number">{{ commentsNumber }}</div>
                    <div class="stat-label">Réponses</div>
                </div>
            </div>

        </div>
        <!-- Comments Section -->

        <div class="comments-section">
            <div class="comments-header">
                <h2>Commentaires</h2>
                <span class="comments-count">
                {{ commentsNumber }} {{ commentsNumber > 1 ? 'réponses' : 'réponse' }}</span>
            </div>

            {% for comment in comments %}

                <div class="comment">
                    <div class="comment-header">
                        <div class="comment-avatar">{{ comment.author.firstName|slice(0, 1)|upper }}{{ comment.author.lastName|slice(0, 1)|upper }}</div>
                        <div class="comment-author-info">
                            <div class="comment-author">{{ comment.author.firstName }} {{ comment.author.lastName }}</div>
                            <div class="comment-date">📅 {{ comment.createdAt|relative_time }}</div>
                        </div>
                    </div>
                    <div class="comment-content">
                        <p>{{ comment.content }}</p>

                    </div>
                </div>

            {% else %}
                <p>Aucun commentaire trouvé ...</p>
            {% endfor %}


        </div>

        <!-- Reply Form -->
        <div class="reply-form">
            <h3>Répondre à ce sujet</h3>
            {{ form_start(form) }}
            <div class="form-group">
                {{ form_widget(form.content, {'attr': {'class': 'form-textarea', 'placeholder': 'Écrivez votre réponse ici...'}}) }}
                {{ form_errors(form.content) }}
            </div>
            <button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
            {{ form_end(form) }}
        </div>
    </div>

{% endblock %}